services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    restart: always
    env_file:
      - .env
    command: bash -c "./run.sh"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  backend:
  postgres_data: